version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    container_name: database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    container_name: pgadmin

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=root
    container_name: api
    volumes:
      - ./src:/app/src
    # command: [ "sh", "./start_after_db.sh" ]
    command: sh -c "sleep 10 && npm run build && npm run migration:run && npm run start:prod"
